version: '3.7'

services: 
    app:
        build: .
        container_name: vue-knights
        volumes: 
            - .:/app
            - /app/node_modules
        working_dir: /app
        ports: 
            - 8080:8080
        command: ['npm', 'run', 'serve']